### ISSUE TITLE
Failed to load resource: the server responded with a status of 500

### ISSUE THREAD

**Issue by eungangku** [hihumanzone/fgpt#6]
![image](https://github.com/hihumanzone/fgpt/assets/77403514/aad09bae-5631-4c50-bc5d-d30d8fcdac97)

Failed to load resource: the server responded with a status of 500.
This error occurs when I try to continue the dialog.

**Comment by hihumanzone** [comment]
I don't manage the API, ask fot support in their discord server. https://discord.gg/pCTprCYhuV
